/*
   25 September 2009 10:20:58
   User: sa
   Server: JUDYVOSTRO
   Database: SeerysNew
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.cus_CustomerDetails ADD
	DefaultOrderType nvarchar(50) NULL
GO
COMMIT
